### ISSUE TITLE
svg on Android

### ISSUE THREAD

**Issue by andylidong** [matc4/react-native-svg-uri#18]
Loading images is slow and crash,What is the solution?

**Comment by matc4** [comment]
Hi @andylidong You are loading an image from an URL or static resource, fails in Android and IOS also?, Happens with all svg's or is only one that fail?

**Comment by Crash--** [comment]
I've the same issue on Android. The only workaround if found ATM is to go to the dev menu and uncheck the "dev mode". With that, the app is far more stable. 

I think the issue comes from react-native-svg. If you take a look at this issue https://github.com/react-native-community/react-native-svg/issues/38 we'll see that people have some stability issues on Android. :(
