### ISSUE TITLE
Can't display svg

### ISSUE THREAD

**Issue by olkeene** [matc4/react-native-svg-uri#26]
Hey guys,
 It doesn't render https://gist.github.com/olkeene/9719da22ef6ee8dbebb8d221a4dec5bd
 No errors or warnings.

Thanks for the help 😄

**Comment by Extracted** [comment]
I'm having the same problem, did you find a solution?

**Comment by olkeene** [comment]
@Extracted Nope

**Comment by AkshatSharda** [comment]
Hi guys,
Export the svg using the adobe illustrator not from the  sketch. It will work for you.

**Comment by Extracted** [comment]
Thank you!

**Comment by lossen** [comment]
Hi!
I faced a similar problem. nothing is displayed :(
I also tried to export the svg using the adobe illustrator, but it didn't help.

"react-native-svg": "^6.0.0",
"react-native-svg-uri": "^1.2.1",
"react": "16.0.0-alpha.12",
"react-native": "0.47.1",

**Comment by prscX** [comment]
Hi @lossen 

Can you please share how you have exported SVG from Illustrator

Based on my experience, please find below steps in order to export SVG from Illustrator: (Steps are based on MAC System)

- Select entire image using (Command + A)
- Double tap on the selection and it will pop you menu options
- Select Group option
- Once it is grouped from the same menu options please select Export Selection option
- Export the image using SVG

Hope this should work. Please let us know in case it does not works

Thanks
Pranav

**Comment by lossen** [comment]
Hi @prscX

I usually keep using File/Save as, then choose svg and needed artboard

> Double tap on the selection and it will pop you menu options 

I tried it but the popup does not appear
Maybe we have different versions of Illustrator... what version you have?

**Comment by prscX** [comment]
Hi @lossen 

I am using Illustrator v21.1.0

Please find below screenshot of menu options when I double tap on image. I suspect it must be some MAC settings.

<img width="222" alt="screen shot 2017-11-16 at 3 44 47 pm" src="https://user-images.githubusercontent.com/28862892/32887226-2f2c04bc-cae9-11e7-9472-f5d65d7a5fc0.png">

Does your exported SVG contains height and width?

Thanks
Pranav

**Comment by lossen** [comment]
Hi @prscX
I have version 16.0.0
But I tried use svg with Homer like in example and Homer not displayed :( 
Also I tried insert svg code into svgXmlData prop and svg displayed!
