### ISSUE TITLE
No ViewManager defined for class RNSVGViewBox

### ISSUE THREAD

**Issue by bear-new** [matc4/react-native-svg-uri#59]
![image](https://cloud.githubusercontent.com/assets/24503317/26281603/69408bde-3e2e-11e7-963c-c49eece32da3.png)

**Comment by bear-new** [comment]
![image](https://cloud.githubusercontent.com/assets/24503317/26281697/eb2f4114-3e31-11e7-8354-a23b54d8ce29.png)

**Comment by matc4** [comment]
Hello, do you link react-native-svg 5.1.8? or some other older version?

**Comment by bear-new** [comment]
@matc4 yes,I have been linked react-native-svg@5.1.8

**Comment by der-kua** [comment]
+1

**Comment by bear-new** [comment]
I  don't npm install react-native-svg-uri, copy index.js and util.js from react-native-svg-uri into the my project. then, I import SvgUri from index.js and use it as an example，It's successful!

**Comment by dk0r** [comment]
I'm uncertain what @bear-new is talking about. Any ideas how to resolve this issue?

**Comment by peterlandry** [comment]
This problem is caused by `react-native-svg-uri` requiring `"react-native-svg": "^4.3.1",`. The current version of `react-native-svg` no longer defines this view manager, but somewhere in the gradle build process the native code for `react-native-svg` included under this package's `node_modules` conflicts with the main version of `react-native-svg`. If you remove `react-native-svg` from this package's `node_modules`, it will compile and run fine. So I think you need to add the specific version in the install instructions, or perhaps use a peer dependency rather than a strict dependency?

**Comment by peterlandry** [comment]
Or, update this package's dependency to a version after `RNSVGViewBox` was removed from `react-native-svg`

**Comment by nguyencaochien** [comment]
So how can we resolve this issue? Change version react-native-svg or something else?

**Comment by matc4** [comment]
Fix in the last release!

**Comment by VanMen** [comment]
I'm using "react-native-svg-uri": "^1.2.3".
Still have to remove below from react-native-svg-uri/package.json

  "peerDependencies": {
    "react-native-svg": "^5.3.0"
  },

after that, I do "gradlew clean" in android directory.
